class Helper
  def self.render_view(filename)
  contents = File.read("views/#{filename}.haml")
  Haml::Engine.new(contents).render
  end

  def self.train_stations
  [
      "Allawah",
      "Arncliffe",
      "Artarmon",
      "Ashfield",
      "Asquith",
      "Auburn",
      "Banksia",
      "Bankstown",
      "Bardwell Park",
      "Bathurst",
      "Beecroft",
      "Bell",
      "Belmore",
      "Berala",
      "Berowra",
      "Beverly Hills",
      "Bexley North",
      "Birrong",
      "Blackheath",
      "Blacktown",
      "Blaxland",
      "Bondi Junction",
      "Bullaburra",
      "Burwood",
      "Cabramatta",
      "Camellia",
      "Campbelltown",
      "Campsie",
      "Canley Vale",
      "Canterbury",
      "Caringbah",
      "Carlingford",
      "Carlton",
      "Carramar",
      "Casula",
      "Central (Sydney)",
      "Chatswood",
      "Cheltenham",
      "Chester Hill",
      "Circular Quay",
      "Clarendon",
      "Clyde",
      "Como",
      "Concord West",
      "Cowan",
      "Cronulla",
      "Croydon",
      "Denistone",
      "Doonside",
      "Dulwich Hill",
      "Dundas",
      "East Hills",
      "East Richmond",
      "Eastwood",
      "Edgecliff",
      "Emu Plains",
      "Engadine",
      "Epping",
      "Erskineville",
      "Fairfield",
      "Faulconbridge",
      "Flemington",
      "Glenbrook",
      "Glenfield",
      "Gordon",
      "Gosford",
      "Granville",
      "Green Square",
      "Guildford",
      "Gymea",
      "Harris Park",
      "Hawkesbury River",
      "Hazelbrook",
      "Heathcote",
      "Holsworthy",
      "Homebush",
      "Hornsby",
      "Hurlstone Park",
      "Hurstville",
      "Ingleburn",
      "Jannali",
      "Katoomba",
      "Killara",
      "Kings Cross",
      "Kingsgrove",
      "Kingswood",
      "Kirrawee",
      "Kogarah",
      "Koolewong",
      "Lakemba",
      "Lapstone",
      "Lawson",
      "Leightonfield",
      "Leumeah",
      "Leura",
      "Lewisham",
      "Lidcombe",
      "Linden",
      "Lindfield",
      "Lisarow",
      "Lithgow",
      "Liverpool",
      "Loftus",
      "Macarthur",
      "Macdonaldtown",
      "Macquarie Fields",
      "Macquarie Park",
      "Macquarie University",
      "Marayong",
      "Marrickville",
      "Martin Place",
      "Mascot",
      "Meadowbank",
      "Medlow Bath",
      "Merrylands",
      "Milsons Point",
      "Minto",
      "Miranda",
      "Mortdale",
      "Mount Colah",
      "Mount Druitt",
      "Mount Kuring-gai",
      "Mount Victoria",
      "Mulgrave",
      "Museum",
      "Marara",
      "Narwee",
      "Newtown",
      "Niagara Park",
      "Normanhurst",
      "North Ryde",
      "North Strathfield",
      "North Sydney",
      "Oatley",
      "Olympic Park",
      "Ourimbah",
      "Padstow",
      "Panania",
      "Parramatta",
      "Pendle Hill",
      "Pennant Hills",
      "Penrith",
      "Penshurst",
      "Petersham",
      "Point Clare",
      "Punchbowl",
      "Pymble",
      "Quakers Hill",
      "Redfern",
      "Regents Park",
      "Revesby",
      "Rhodes",
      "Richmond",
      "Riverstone",
      "Riverwood",
      "Rockdale",
      "Rooty Hill",
      "Rosehill",
      "Roseville",
      "Rydalmere",
      "Schofields",
      "Sefton",
      "Seven Hills",
      "Springwood",
      "St James",
      "St Leonards",
      "St Marys",
      "St Peters",
      "Stanmore",
      "Station",
      "Strathfield",
      "Summer Hill",
      "Sutherland",
      "Sydenham",
      "Tascott",
      "Telopea",
      "Tempe",
      "Thornleigh",
      "Toongabbie",
      "Town Hall",
      "Tuggerah",
      "Turramurra",
      "Turrella",
      "Valley Heights",
      "Villawood",
      "Vineyard",
      "Wahroonga",
      "Waitara",
      "Warrawee",
      "Warrimoo",
      "Warwick Farm",
      "Waterfall",
      "Waverton",
      "Wentworth Falls",
      "Wentworthville",
      "Werrington",
      "West Ryde",
      "Westmead",
      "Wiley Park",
      "Windsor",
      "Wolli Creek",
      "Wollstonecraft",
      "Wondobyne",
      "Woodford",
      "Woolooware",
      "Woy Woy",
      "Wynyard",
      "Wyong",
      "Yagoona",
      "Yennora",
      "Zig Zag"
    ]
  end
end
